/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import java.util.PriorityQueue;
import java.util.Scanner;

import client.commands.Command;
import client.database.DataReader;
import client.database.Database;
import client.input.CommandParser;
import client.labwork.LabWork;

public class App {

    public static void main(String[] args) {

        CommandParser rc = new CommandParser();
        System.out.print("Для просмотра доступных команд введите help.");
        Scanner scanner = new Scanner(System.in);
        while (true) {
            Command command = rc.recieveCommand(scanner);

        }
        
    }
}
