/*
 * This source file was generated by the Gradle 'init' task
 */
package lab1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.lang.annotation.Target;

class DFATest {

    @Test void emptyString() {
        assertFalse(DFA.accepts(""));
    }

    @Test void continsOnlyOneString() {
        assertFalse(DFA.accepts("bbcabbc"));
    }

    @Test void containsOnlyTwoString() {
        assertFalse(DFA.accepts("baabbc"));
    }

    @Test void containsOnlyThreeString() {
        assertFalse(DFA.accepts("bccbbaaac"));
        assertFalse(DFA.accepts("abbcbaa"));
    }

    @Test void containsAtStartAndEnd() {
        assertTrue(DFA.accepts("aabccbaa"));
    }

    @Test void consistOfFull() {
        assertTrue(DFA.accepts("aaaa"));
    }

    @Test void containsFullAtRandom() {
        assertTrue(DFA.accepts("bccbaabbcaa"));
    }

    @Test void containsFullAtStartAndRandom() {
        assertTrue(DFA.accepts("aabbcaabcc"));
    }

}
