/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length != 1) {
        } else {
            if (args[0].equals("client")) {
                app.client.Client.main(null);
            } else if (args[0].equals("server")) {
                app.server.Server.main(null);
            }
            return;
        }
        System.out.println("Передайте аргумент, (client/server).");
    }
}
