/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.PriorityQueue;
import java.util.Scanner;

import server.database.DataReader;
import server.database.Database;
import server.labwork.LabWork;
import server.network.Receiver;

public class App {

    public static void main(String[] args) {

        Database dataBase = new Database();
        DataReader dataReader = new DataReader(dataBase);

        PriorityQueue<LabWork> priorityQueue = dataReader.read();
        Long maxId = 0l;

        for (LabWork lab : priorityQueue) {
            if (lab.getId() > maxId) {
                maxId = lab.getId();
            }
        }

        Receiver rc = new Receiver(priorityQueue);
        Receiver.maxId = maxId;

        try {

            ServerSocket socket = new ServerSocket(7777);
            Socket clientSocket = socket.accept();
            Scanner scanner = new Scanner(clientSocket.getInputStream());

            while (true) {
                rc.recieveCommand(scanner);
            }

        } catch (IOException exception) {
            System.out.println(exception.getStackTrace());
        }
        
    }
}
